name: Install dependencies, run Prettier and EsLint + build & deploy on merge main

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Prettier and ESLint
        run: |
          npm run format-check
          npm run lint

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and deploy to GitHub Pages
        run: npm run build-and-deploy
